#!/bin/bash

if [[ ! -d node_modules ]]; then
	npm install yui@3.5.1 express request hbs handlebars gzip optimist formidable mkdirp;
fi

echo ===;
whoami;
echo ===;

killall node;

rm -rf test/init;
mkdir test/init;

rm -rf test/files;
mkdir test/files;
cp test/groups.json test/files;

node manager.js --config test/config/manager-localhost-admin.json --test test/init/manager.ready &
node combo.js --config test/config/combo.json --test test/init/combo.ready &
node combo-dev.js --config test/config/combo-dev.json --test test/init/combo-dev.ready &

cd test;

perl init-wait.pl &&
perl test-upload-localhost-admin.pl &&
perl test-browse.pl &&
perl test-combo.pl &&
perl test-combo-dev.pl &&
killall node &&
true; # rm -rf test/init test/files;
